### ISSUE TITLE
[REQ]: www.lcsc.com

### ISSUE THREAD

**Issue by salfter** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10269]
### Website URL

www.lcsc.com

### What browser are u using?

Chromium 120

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #9703.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
