### ISSUE TITLE
Trying to fix as much websites as possible.

### ISSUE THREAD

**Issue by azgaresncf** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10310]
# Goal
Thanks to @OhMyGuus, I am going to fix as many websites AS POSSIBLE.

I know this is going to be an enormous process, but I will do it.

(PS: if you want to help me, DM me on Discord: `azgaresncf`.)

**Comment by azgaresncf** [comment]
PS.2: All the fixes are available here: https://github.com/azgaresncf/I-Still-Dont-Care-About-Cookies

**Comment by inson1** [comment]
@azgaresncf Thank you! Why don you create PR even as draft and add there "fixes:" issues?

**Comment by azgaresncf** [comment]
> @azgaresncf Thank you! Why dont you create PR even as draft and add there "fixes:" issues?

Because I'm doing it locally right now. Once I will have a lot of websites fixed, I will create the PR.

**Comment by inson1** [comment]
@azgaresncf people would see it better in PRs than issues, plus we would see what issues are done - you could link issues :)

**Comment by azgaresncf** [comment]
> @azgaresncf people would see it better in PRs than issues, plus we would see what issues are done - you could link issues :) 

Don't worry, I will do it ;)
