### ISSUE TITLE
[Feature Request] Make it available from addons.mozilla.org

### ISSUE THREAD

**Issue by bat999** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10341]
Hi
This addon works OK for me with Android Firefox-Beta using a "Custom Add-on collection".
Please fix it to work with addons.mozilla.org (AMO).
Info is here ---> https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/

No hurry for this.
Custom Add-on collection works OK.
But AMO would make the addon available to more Android Firefox users.

**Comment by SnowballV** [comment]
@bat999,
I'm not sure if I understand correctly.
Is the add-on not available for Android on AMO?
It says, "Available on Firefox for Android".
[https://addons.mozilla.org/en-US/firefox/addon/istilldontcareaboutcookies/](https://addons.mozilla.org/en-US/firefox/addon/istilldontcareaboutcookies/)

**Comment by bat999** [comment]
Hi
Yes it does say "Available on Firefox for Android".
I suppose that means with a "Custom Add-on collection".

You got it about Android page https://addons.mozilla.org/en-US/android/
This is what it looks like when using Android phone...
![AMO](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/assets/640761/f865731f-21a5-4d19-aaf9-35e17af0abe5)

**Comment by SnowballV** [comment]
Before your recent edit, you wrote, "This is what it looks like when using Android phone..." and there was a screenshot added.
When I visit 'Firefox for Android extensions' with Firefox desktop, I get those same search results for 'cookie'. No 'I still don't care about cookies'.

**Comment by bat999** [comment]
**@SnowballV** 
Hi
Here it is again!

![AMO](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/assets/640761/60b83c26-d959-44d2-87d0-e9746925ff48)

**Comment by krystian3w** [comment]
Share link for desktop instead.

https://addons.mozilla.org/firefox/addon/istilldontcareaboutcookies/

**Comment by OhMyGuus** [comment]
Didn't know this was available yet, might need to make a release first before it shows up.

**Comment by OhMyGuus** [comment]
It seems to be fixed now, it shows up on the other page, apperently I needed to change the version as well.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2969

Maybe anybody started similar change logic in addon.

**Comment by bat999** [comment]
Yes, it shows in Android search now.
;-)
