### ISSUE TITLE
[REQ]: www.saturn.de

### ISSUE THREAD

**Issue by redfave** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10423]
### Website URL

www.saturn.de

### What browser are u using?

Firefox 120.0

### Version

1.1.1

### Notes

Cookie banner only visible after disabling the extension. Otherwise, the website is not scrollable.

**Comment by Zoriot** [comment]
Works fine with https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/pull/10435.
