### ISSUE TITLE
[REQ]: www.eurostar.com

### ISSUE THREAD

**Issue by P-eMartin** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10424]
### Website URL

www.eurostar.com

### What browser are u using?

Firefox 120.0

### Version

1.1.1

### Notes

Website not accessible because of extension.

**Comment by Zoriot** [comment]
Duplicate of https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/8653.
