### ISSUE TITLE
[REQ] Site request: auto-motor-und-sport.de

### ISSUE THREAD

**Issue by Termuellinator** [OhMyGuus/I-Still-Dont-Care-About-Cookies#1042]
**Website URL(s)**

- https://www.auto-motor-und-sport.de
- https://www.auto-motor-und-sport.de/neuheiten/mercedes-amg-s63e-2021-top-s-klasse-nur-mit-hybrid/ as an example

**Browser**
[x] Firefox
[x] Chrome

**Extension version**
V1.1.0

Website itself works fine, but you can't access the image gallery if isdcac is active and cookie-dialogue hasn't been accepted.

Thanks for all the work on this occasion ;)

**Comment by OhMyGuus** [comment]
Found the cookie banner but it's placed in the slow queue. 
 This is most likely because it requires more work than just a CSS filter.

**Comment by azgaresncf** [comment]
already fixed
