### ISSUE TITLE
[REQ]: https://www.br.de/nachrichten/

### ISSUE THREAD

**Issue by dreirund** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10469]
### Website URL

https://www.br.de/nachrichten/

### What browser are u using?

Firefox 122.0

### Version

1.1.1

### Notes

https://www.br.de/nachrichten/ needs that the extension is disabled to interact with the cookie banner so that the webpage can be scrolled.

With the extension enabled, the site cannot be scrolled.

(https://www.br.de/ works, but not https://www.br.de/nachrichten/ and sub-pages.)

**Comment by OhMyGuus** [comment]
Already fixed in development, will be in the next release.

**Comment by OhMyGuus** [comment]
Fixed in V1.1.2, if still not working report it again or @OhMyGuus
