### ISSUE TITLE
sold to avast, not actual, has to be changed

### ISSUE THREAD

**Issue by ONE11111111ONE** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10514]
Good Night,
as you all know daniel k. sold i don't care about cookies to avast in the past. i had been using this add on since it existed many years ago. 

I was shocked, yet. the situation is, avast got together with norton or symantec and they got bought by another company. 
https://en.wikipedia.org/wiki/Gen_Digital
they even own ccleaner (avast) and Avira now. 
Its a supertech company. you cannot use anything they offer. 
And many businesses use norton or symantec endpoint protection, what a mess.

it should be updated in the readme, since it's not an avast issue anymore.

cheers have a good night

**Comment by ONE11111111ONE** [comment]
Whst does it mean when your eyes are watching it? Hope guus sees it too. Itd just the truth.

**Comment by obfuscated-loop** [comment]
@ONE11111111ONE I understand your frustration but try to remain civil when talking about stuff like this as it dampens your point - I have submitted a PR however because I think you raise a valid point.

**Comment by OhMyGuus** [comment]
Oof!

Merged the suggestions from #10608
