### ISSUE TITLE
[REQ]: www.autoweek.nl

### ISSUE THREAD

**Issue by M1Aston** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10543]
### Website URL

www.autoweek.nl

### What browser are u using?

Firefox 121.0

### Version

1.1.1

### Notes

https://www.autoweek.nl/autonieuws/artikel/deze-autootjes-waren-er-al-als-vierdeurs-toen-dat-nog-bijzonder-was/

In the cookie settings "Social media" has to be accepted\allowed, otherwise pictures that are part of the articles on this websites won't load at all.

**Comment by Zoriot** [comment]
Seems to be fixed on Version 1.1.2. @M1Aston

**Comment by OhMyGuus** [comment]
Not fixed in v1.1.2, will be in v1.1.3
