### ISSUE TITLE
[REQ]: www.reddit.com

### ISSUE THREAD

**Issue by freakedenough** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10579]
### Website URL

www.reddit.com

### What browser are u using?

Firefox 121.0

### Version

1.1.1

### Notes

Just hid the accept button, idk.
![grafik](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/assets/93607470/1db67cfe-d279-40cd-b904-62b942e6e5ee)

"Reddit and its partners use cookies and similar technologies to provide you with a better experience.
By accepting all cookies, you agree to our use of cookies to deliver and maintain our services and site, improve the quality of Reddit, personalize Reddit content and advertising, and measure the effectiveness of advertising.
By rejecting non-essential cookies, Reddit may still use certain cookies to ensure the proper functionality of our platform.
For more information, please see our [Cookie Notice](https://reddit.com/en-us/policies/cookies) and our [Privacy Policy](https://reddit.com/en-us/policies/privacy-policy)."

**Comment by OhMyGuus** [comment]
already fixed in v1.1.2
