### ISSUE TITLE
[REQ] www.ebrarbilgisayar.com

### ISSUE THREAD

**Issue by gototheskinny** [OhMyGuus/I-Still-Dont-Care-About-Cookies#1058]
[https://www.ebrarbilgisayar.com](https://www.ebrarbilgisayar.com)
**Chrome 107**

**1.1.0**

[adguard repo solved issue](https://github.com/AdguardTeam/AdguardFilters/issues/136814)

**Comment by OhMyGuus** [comment]
Found the cookie banner but it's placed in the slow queue. 
 This is most likely because it requires more work than just a CSS filter.
