### ISSUE TITLE
[REQ]: smarterkram.de

### ISSUE THREAD

**Issue by bas89** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10711]
### Website URL

smarterkram.de

### What browser are u using?

Chromium

### Version

1.1.2

### Notes

Website unusable using the extension.

**Comment by inson1** [comment]
/notfound
@bas89 what doesnt work?

**Comment by bas89** [comment]
Sorry for the confusion. I thought the whole page is inresponsive, but it is just not scrolling (with mouse or arrow keys).

Disabling the extension makes the cookie banner pop up, after accepting scrolling works. I try to reproduce it with all my other extensions disabled: Still the same issue.

Thanks for your time.
