### ISSUE TITLE
[REQ]: fostips.com

### ISSUE THREAD

**Issue by Reno-Sifana** [OhMyGuus/I-Still-Dont-Care-About-Cookies#10761]
### Website URL

fostips.com

### What browser are u using?

Chromium 120

### Version

1.1.3

**Comment by OhMyGuus** [comment]
/notfound

The cookie banner in the left bottom corner isn't showing for me when I have the extension enabled, where do u still see this banner?

**Comment by Reno-Sifana** [comment]
> /notfound
> 
> The cookie banner in the left bottom corner isn't showing for me when I have the extension enabled, where do u still see this banner?

As i recall i found on main homepage. Unfortunately, i forget to capture a screenshot yet. When i visit fostips.com once again the cookies banner is gone.
