### ISSUE TITLE
[REQ]: huutokaupat.com

### ISSUE THREAD

**Issue by lamtonylam** [OhMyGuus/I-Still-Dont-Care-About-Cookies#1154]
### Website URL

huutokaupat.com

### What browser are u using?

Chromium 108

### Version

1.1.0

### Notes

![image](https://user-images.githubusercontent.com/63186670/207592014-da1ac2a5-329e-4089-88a1-1064f7bbb764.png)

**Comment by azgaresncf** [comment]
already fixed
