### ISSUE TITLE
[BUG] Anonymously report cookie warning doesnt work as intendet

### ISSUE THREAD

**Issue by inson1** [OhMyGuus/I-Still-Dont-Care-About-Cookies#11899]
![j9Hhay3g8F](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/assets/75314629/72c62fb1-254b-4ea6-9821-4f88706c2a9c)

I wanted report website and this happened after clicking  on send report, but website is here https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/11898

 @OhMyGuus

**Comment by OhMyGuus** [comment]
Thanks a lot fixed 👍
