### ISSUE TITLE
[REQ] Can you add a filter for Ublock Origin

### ISSUE THREAD

**Issue by STVGecko** [OhMyGuus/I-Still-Dont-Care-About-Cookies#133]
Hello, can you add a filter (the list) in Ublock Origin like the "i don't care about cookie" ? 

Like this : https://www.i-dont-care-about-cookies.eu/abp/

Thanks :-)

**Comment by OhMyGuus** [comment]
We where not able to find the cookie banner, it might already be fixed.
 If there is still a banner please resumbit and add a comment where it is thanks!

**Comment by krystian3w** [comment]
Why this https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/labels/feature%20request was closed by bot?

**Comment by krystian3w** [comment]
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1177

**Comment by brian6932** [comment]
Because it's a duplicate of the other issue he linked?

**Comment by krystian3w** [comment]
This is older than https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/1177

- Oct 20, 2022 vs:
- Dec 16, 2022 

You can link issue older than Oct 20, 2022?
