### ISSUE TITLE
[REQ] Site request: seb.se

### ISSUE THREAD

**Issue by realityexists** [OhMyGuus/I-Still-Dont-Care-About-Cookies#1348]
**Website URL(s)**
https://seb.se/

**Browser**
Chrome 108.0.5359.125

**Extension version**
V1.1.0

The cookie overlay is hidden, but none of the links on the site can be clicked on.

**Comment by realityexists** [comment]
Thank you so much @OhMyGuus ! I can finally remove the exception for seb.se.

**Comment by OhMyGuus** [comment]
Thanks for the report 
 Added support for it in the next update :)
