### ISSUE TITLE
[FEATURE] Translation support using Crowdin or something similar

### ISSUE THREAD

**Issue by OhMyGuus** [OhMyGuus/I-Still-Dont-Care-About-Cookies#136]
Add a easy way to support community Translations for example using Crowdin or POEditor or something like that.

**Comment by Cwpute** [comment]
I suggest using [Weblate](https://weblate.org/fr/) over Crowdin, which offers to host the localization tools for free for FOSS projects (or alternatively allows to freely self-host it).

**Comment by OhMyGuus** [comment]
> 

Late response thanks for the recommendation, we decided on Crowdin for now (mostly since my other project is also using Crowdin). I still put it in my list to test it out on a later date, since self hosted seems quite interesting :)
