### ISSUE TITLE
[REQ] https://www.gross-zimmern.de/kultur-freizeit-sport/freizeit-sport/hallenbad/

### ISSUE THREAD

**Issue by Buchhems** [OhMyGuus/I-Still-Dont-Care-About-Cookies#1474]
https://www.gross-zimmern.de/kultur-freizeit-sport/freizeit-sport/hallenbad/
With ISDCAC installed one cannot scroll down the page. If you open the page in a "normal" browser a custom cookie warning is shown.

**Comment by OhMyGuus** [comment]
Thanks for the report 
 Added support for it in the next update :)
