### ISSUE TITLE
[REQ] Site request: omroepwest.nl

### ISSUE THREAD

**Issue by Gandalf-The-Wise** [OhMyGuus/I-Still-Dont-Care-About-Cookies#1477]
**Website URL(s)**

- https://www.omroepwest.nl/

**Browser**
[ ] Firefox
[ ] Chrome
[x] Edge

**Extension version**
V1.0.9

You must enable all cookies before you can see the video's on this local news site.
When whitelisting this site I get the cookie banner, can accept and play the video's.

**Comment by OhMyGuus** [comment]
Found the cookie banner but it's placed in the slow queue. 
 This is most likely because it requires more work than just a CSS filter.

**Comment by Gandalf-The-Wise** [comment]
Thanks for looking into this issue, for now I just whitelist this website.
