### ISSUE TITLE
[REQ]: www.onliner.by

### ISSUE THREAD

**Issue by Versus-alpha** [OhMyGuus/I-Still-Dont-Care-About-Cookies#15616]
### Website URL

www.onliner.by

### What browser are u using?

Firefox 130.0

### Version

1.1.4

**Comment by SoldierFace** [comment]
This might help:This file might fix it
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive
