### ISSUE TITLE
[REQ]: tina.io

### ISSUE THREAD

**Issue by NoahBK** [OhMyGuus/I-Still-Dont-Care-About-Cookies#15774]
### Website URL

tina.io

### What browser are u using?

Google Chrome 130

### Version

1.1.4

### Notes

![axCj1x5](https://github.com/user-attachments/assets/0fef8eb0-cd01-4958-89d2-34079b5949a6)

**Comment by azgaresncf** [comment]
add the cookie 
`consentGiven: {%22ad_storage%22:false%2C%22ad_personalization%22:false%2C%22analytics_storage%22:false%2C%22ad_user_data%22:false}`

**Comment by NoahBK** [comment]
That sadly didn't seem to fix the issue. I could be doing something wrong, but when I put in `consentGiven: {%22ad_storage%22:false%2C%22ad_personalization%22:false%2C%22analytics_storage%22:false%2C%22ad_user_data%22:false}` into Tina.io's cookie value field, it didn't seem to change anything upon reload of the site.

**Comment by azgaresncf** [comment]
pretty weird

**Comment by azgaresncf** [comment]
![{B0FE8ABD-2BB3-492F-957C-A49A4A1F67D6}](https://github.com/user-attachments/assets/439f7527-72c9-4d49-9cce-82dc010fec49)
it personally works

**Comment by NoahBK** [comment]
I may have just copy and pasted it wrong, because going back in and pasting the same thing you had given me earlier now seems to work. 
![nM5d3ms](https://github.com/user-attachments/assets/0d5875e5-e5eb-4558-8b1f-6cc21e91ec52)
