### ISSUE TITLE
[REQ]: www.gmx.net

### ISSUE THREAD

**Issue by Buddel1** [OhMyGuus/I-Still-Dont-Care-About-Cookies#15809]
### Website URL

www.gmx.net

### What browser are u using?

Firefox 132.0

### Version

1.1.4

### Notes

![GMX-cookie-warning](https://github.com/user-attachments/assets/92fa0502-5ed0-46b8-a423-6cdb9ab7b4c3)
GMX cookie warning, screenshot include.

**Comment by azgaresncf** [comment]
It fully works

**Comment by Buddel1** [comment]
If it fully worked, I would not get this consent message, would I?

**Comment by azgaresncf** [comment]
![image](https://github.com/user-attachments/assets/8a751582-630b-473a-beb7-6b627dd484a0)
i've downloaded the zip addon from github and load it to chrome and it works
(https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/archive/refs/heads/master.zip)

**Comment by Buddel1** [comment]
Please read my first post; I do not use Chrome (and never will). Apart from that, you can see a screenshot there, which makes it sufficiently clear that it does not work.

**Comment by azgaresncf** [comment]
Yes

**Comment by azgaresncf** [comment]
https://github.com/user-attachments/assets/9a81b16a-dfa9-4470-bd5c-43841646d8fd
I've downloaded the extension from the Firefox store and it works

**Comment by Buddel1** [comment]
Maybe it works for you, but it does not work here, so it does not "fully" work, as you stated above.

**Comment by Mrgaton** [comment]
works for me too but a bit slow

**Comment by Mrgaton** [comment]
maybie you visited on mobile?

**Comment by Buddel1** [comment]
It does not work here, so I will have to look for an alternative to ISDCAC. Anyway, thanks for your replies, guys.

**Comment by Buddel1** [comment]
PS: I removed ISDCAC and added two rules to uBO - fixed!
