### ISSUE TITLE
[REQ]: www.tenforums.com

### ISSUE THREAD

**Issue by bpsib** [OhMyGuus/I-Still-Dont-Care-About-Cookies#1620]
### Website URL

www.tenforums.com

### What browser are u using?

Chromium 108

### Version

1.0.9

### Notes

I get an annoying message saying `You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page.` on Windows 10 Forums since installing this. Disabling the extension for the website then dismissing the cookie warning removes the message.

![image](https://user-images.githubusercontent.com/5899155/211940246-058518c2-ac94-4375-9c7c-26f80bce4fa3.png)

**Comment by bpsib** [comment]
I have just found this only happens if I also have Adblock Plus active at the same time.

**Comment by krystian3w** [comment]
Bad is generic block:

```adb
||fundingchoices.google.com^
||fundingchoicesmessages.google.com^
```

**Comment by krystian3w** [comment]
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/labels/automated-verticalscrollbug-found where?

**Comment by OhMyGuus** [comment]
> [ automated-verticalscrollbug-found](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/labels/automated-verticalscrollbug-found) where?

Nowhere my bot was blocked so it was checking on a blocked page xD
Can't seem to reproduce this issue tho

**Comment by OhMyGuus** [comment]
please @OhMyGuus if the issue still exists
