### ISSUE TITLE
[REQ] Site request: 8020.net

### ISSUE THREAD

**Issue by MarkKahn** [OhMyGuus/I-Still-Dont-Care-About-Cookies#1800]
**Website URL(s)**

- [8020.net](https://8020.net/deflection-calculator)

**Browser**
[ ] Firefox
[x] Chrome

**Extension version**
V1.1.0

Several scripts are getting blocked for some unknown reason preventing the JS on the page from working

**Comment by OhMyGuus** [comment]
Thanks for the report 
 Added support for it in the next update :)
