### ISSUE TITLE
[REQ] Site request: https://www.rnd.de/

### ISSUE THREAD

**Issue by OldPixelReaper** [OhMyGuus/I-Still-Dont-Care-About-Cookies#2261]
**Website URL(s)**

- https://www.rnd.de
- https://www.ostsee-zeitung.de

**Browser**
[x] Firefox
109.1

**Extension version**
V1.1.0
The page sometimes works, sometimes doesn't and displays blank.

**Comment by OhMyGuus** [comment]
We where not able to find the cookie banner or might already be fixed in a new update.
 If there is still a banner in the next release please resumbit and add a comment where it is thanks!
