### ISSUE TITLE
disabled by google in chrome

### ISSUE THREAD

**Issue by grantiago** [OhMyGuus/I-Still-Dont-Care-About-Cookies#2262]
this morning, 2023-02-12, google disabled the extension on my chrome install. Also getting a 404 trying to visit the link in the extensions marketplace. violation of terms.

**Comment by Meins321** [comment]
Yes here too somehow they delted the extension.. why that is trash

**Comment by Terafugia** [comment]
2023-02-12 - Still working With Edge. As Grantiago mentioned there is no explanation. The Dev might no more.

**Comment by OhMyGuus** [comment]
Dupe of #2253, sadly our extension got removed by google because we didn't have a privacy policy at first. However I added it but they still decided to remove it so yeah...
