### ISSUE TITLE
[REQ]: my.parallels.com

### ISSUE THREAD

**Issue by sebisteiner** [OhMyGuus/I-Still-Dont-Care-About-Cookies#2435]
### Website URL

my.parallels.com

### What browser are u using?

Firefox 110.0

### Version

1.1.1

### Notes

Cookie banner not visible - cannot click "Verify and Continue".

**Comment by OhMyGuus** [comment]
Where did u find the button required button "Verify and Continue"? 

-- Note for me  --
local storage: 
cp-accept:  {"value":1,"expire":null}

**Comment by sebisteiner** [comment]
It's on the Two-step Verification page. But I just retested it and saw that it's not a problem with your extension.

If I paste the code from my password manager the button stays disabled. I have to type it 😕 

Shall I close this issue?

<img width="715" alt="grafik" src="https://user-images.githubusercontent.com/3097292/221493535-3cfb7ca9-e216-47e2-99db-11417ae21ac5.png">
