### ISSUE TITLE
[REQ]: www.sw-lindau.de

### ISSUE THREAD

**Issue by AndriyAstakhov** [OhMyGuus/I-Still-Dont-Care-About-Cookies#2587]
### Website URL

www.sw-lindau.de

### What browser are u using?

Latest Chrome on Windows 11

### Version

1.1.1

### Notes

gray overlay

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #2586.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
