### ISSUE TITLE
[REQ]: www.strato-hosting.co.uk

### ISSUE THREAD

**Issue by XoloitzcuintiI** [OhMyGuus/I-Still-Dont-Care-About-Cookies#2630]
### Website URL

www.strato-hosting.co.uk

### What browser are u using?

Firefox 110.0

### Version

1.1.1

### Notes

Big cookie banner that prevents interaction with website until a selection is made.

**Comment by OhMyGuus** [comment]
![image](https://user-images.githubusercontent.com/12090928/221673816-99f599d8-071e-45a0-bc66-97d7d23c0248.png)
Weird it seems to block that banner for me just fine, can u check it it looks like the one on the screenshot

**Comment by XoloitzcuintiI** [comment]
Just checked again, and now the pop-up is gone.

**Comment by OhMyGuus** [comment]
> Just checked again, and now the pop-up is gone.

Weird but at least it's working now
