### ISSUE TITLE
[REQ]: www.sinsay.com

### ISSUE THREAD

**Issue by Aleksanderro** [OhMyGuus/I-Still-Dont-Care-About-Cookies#303]
### Website URL

www.sinsay.com

### What browser are u using?

Firefox 106.0

### Version

1.0.8

### Notes

Site shadowed, unable to click anywhere untill disabling addon and clicking into cookies section.

**Comment by appeasementPolitik** [comment]
Works for me

**Comment by OhMyGuus** [comment]
Mmh very weird this one should just work fine, because it uses request blocking.
