### ISSUE TITLE
[REQ]: www.whatsapp.com

### ISSUE THREAD

**Issue by Deedikjupijn** [OhMyGuus/I-Still-Dont-Care-About-Cookies#361]
### Website URL

www.whatsapp.com

### What browser are u using?

Chromium 107 (Brave)

### Version

1.0.8

### Notes

<img width="623" alt="image" src="https://user-images.githubusercontent.com/67846839/200091766-7fa1a0ef-a5bf-4f47-b443-674e7de8c95b.png">

**Comment by OhMyGuus** [comment]
Very weird that u are getting this banner, it should have support for it.

**Comment by Deedikjupijn** [comment]
Ye I thought it was weird too, if you need more information about my browser or anything just ask btw.
