### ISSUE TITLE
[REQ]: www.doctolib.de

### ISSUE THREAD

**Issue by jraxxo** [OhMyGuus/I-Still-Dont-Care-About-Cookies#4108]
### Website URL

www.doctolib.de

### What browser are u using?

Firefox 111.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #2857.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
