### ISSUE TITLE
[REQ]: www.reddit.com

### ISSUE THREAD

**Issue by hydermanpete** [OhMyGuus/I-Still-Dont-Care-About-Cookies#4316]
### Website URL

www.reddit.com

### What browser are u using?

Firefox 113.0

### Version

1.1.1

### Notes

Huge Cookied warning at top of screen

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #1416.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
