### ISSUE TITLE
[REQ]: www.theguardian.com - site interaction broken

### ISSUE THREAD

**Issue by scheinercc** [OhMyGuus/I-Still-Dont-Care-About-Cookies#472]
### Website URL

www.theguardian.com

### What browser are u using?

Firefox 107.0

### Version

1.0.10

### Notes

Sometimes a fullpage transparent overlay
```
<div id="sp_message_container_665687" ...>
```
is not staying active, making it impossible to clicking any page element

Seems to be the container `div` for this iframe
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/817856/201010504-e85aaba7-35bc-46ac-8918-b2c627b40c03.png">
<img width="998" alt="image" src="https://user-images.githubusercontent.com/817856/201010541-4a2b6eb8-5749-4c07-afe8-b6574b8b40b2.png">

Context menu while overlay is active, context-click not reaching the headline link
<img width="273" alt="image" src="https://user-images.githubusercontent.com/817856/201009836-dd597e15-795e-4d42-96e5-65f8ae86a323.png">

Context menu after I set the overlay manually to `display: none`, context-click reaching the headline link
<img width="397" alt="image" src="https://user-images.githubusercontent.com/817856/201009874-f3018daa-dbf2-47f3-b144-d72904bf8ac5.png">

**Comment by appeasementPolitik** [comment]
Odd, for me the div is called `sp_message_container_717122`

`'div[id^="sp_message_container_"]'`

can match both cases

**Comment by OhMyGuus** [comment]
The bigger issue is that the the overlay is quite different from mine and it doesn't click it away in the clickhandler. 
![image](https://user-images.githubusercontent.com/12090928/201087915-914e7e17-653e-4096-8343-bb7da17fe3a5.png)

Will try it with a vpn & some locations to figure it out, thanks for the report with the screenshot!

**Comment by scheinercc** [comment]
Have you had any luck yet? Seems to be the AU version and not happening for me on UK, but could also be A/B testing that I only sometimes hit it. 
https://www.theguardian.com/au
Let me know if you need more info or testing please.
