### ISSUE TITLE
[REQ]: www.golem.de

### ISSUE THREAD

**Issue by nicolaasjan** [OhMyGuus/I-Still-Dont-Care-About-Cookies#477]
### Website URL

www.golem.de

### What browser are u using?

Firefox 106.0.5

### Version

1.0.10

### Notes

![Screenshot 2022-11-10 at 10-42-53 Golem de IT-News für Profis](https://user-images.githubusercontent.com/14093220/201057210-3597dd7a-be8f-42e8-9215-74eca374797a.png)
Text in red says:
`The consent dialog could not be loaded correctly, consent is only provisional.  Troubleshooting information can be found here.`

Then I tried a clean profile:

![Screenshot 2022-11-10 at 10-54-08 Golem de IT-News für Profis](https://user-images.githubusercontent.com/14093220/201059602-f81e67c2-2637-4fb8-a1f3-8a9e2eac89fa.png).

Now the button worked.

[Edit]
No issue in Chromium.

**Comment by OhMyGuus** [comment]
Mmh, it seems to me that it doesn't like the display none, or that it isn't excluding the cmp correctly.
Need to test it a bit more to figure out fully what the issue seems to be, the sad part is that it seems to be quite random

**Comment by azgaresncf** [comment]
already fixed

**Comment by nicolaasjan** [comment]
Thanks!
Loading from source worked. 🙂
