### ISSUE TITLE
[REQ]: www.nytimes.com

### ISSUE THREAD

**Issue by hensou** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5028]
### Website URL

www.nytimes.com

### What browser are u using?

Firefox 115.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3128.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
