### ISSUE TITLE
[REQ]: www.temu.com

### ISSUE THREAD

**Issue by dreamAviator** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5290]
### Website URL

www.temu.com

### What browser are u using?

Firefox 114.0

### Version

1.1.1

### Notes

The cookie banner is okay, it has a button to reject all cookies. But still, would be cool if you fix it.
Thank you for this Add-On!!! <3

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #4770.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
