### ISSUE TITLE
[REQ]: www.awwwards.com

### ISSUE THREAD

**Issue by Theblockbuster1** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5306]
### Website URL

www.awwwards.com

### What browser are u using?

Chromium 114

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #1336.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
