### ISSUE TITLE
[REQ]: pacstall.dev

### ISSUE THREAD

**Issue by Reno-Sifana** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5533]
### Website URL

pacstall.dev

### What browser are u using?

Firefox 114.0

### Version

1.1.1

**Comment by saenai255** [comment]
Hello,

I am one of the developers working on this website. I would like to clarify that our use of cookies is not intrusive, and you only need to click on "Ok, I understand" once. We utilize cookies to store theme settings and, with your consent, track usage metrics using the open-source and well-known tracking software Matomo.

Adding a cookie bypass would likely disrupt the website's functionality either now or in future releases, and it may lead users to submit bug reports to us.

Therefore, I kindly request you to reconsider excluding `https://pacstall.dev` from this extension.

Thank you.
