### ISSUE TITLE
[REQ]: www.hl.co.uk

### ISSUE THREAD

**Issue by bpsib** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5971]
### Website URL

www.hl.co.uk

### What browser are u using?

Firefox 115.0

### Version

1.1.1

### Notes

No scrollbar until I disable then dismiss the notice.

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3943.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
