### ISSUE TITLE
[REQ]: ai.meta.com

### ISSUE THREAD

**Issue by Dimitris-Konstantakis** [OhMyGuus/I-Still-Dont-Care-About-Cookies#5997]
### Website URL

ai.meta.com

### What browser are u using?

Google Chrome 115

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #5813.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
