### ISSUE TITLE
[REQ]: www.vogelsbergkreis.de

### ISSUE THREAD

**Issue by HolgerAusB** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6123]
### Website URL

www.vogelsbergkreis.de

### What browser are u using?

Firefox 115.0

### Version

1.1.1

### Notes

The website is not usable when ISDCAC is active. No scrolling or clicking links or buttons

**Comment by OhMyGuus** [comment]
fixed

**Comment by HolgerAusB** [comment]
not fixed with 1.1.2. Scrolling is possible now, but no clicking on links or buttons

**Comment by azgaresncf** [comment]
> not fixed with 1.1.2. Scrolling is possible now, but no clicking on links or buttons

It will be fixed on #10665.

By now, you can either add this filter to the code
`"vogelsbergkreis.de": { s: "cookie-consent-dialogue{display:none!important}", c: 85 },`
or manually block the "cookie-consent-dialogue" tag.
