### ISSUE TITLE
[REQ]: www.notion.so

### ISSUE THREAD

**Issue by Kuenlun** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6145]
### Website URL

www.notion.so

### What browser are u using?

Firefox 115.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #1267.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
