### ISSUE TITLE
[REQ]: www.ovh.com

### ISSUE THREAD

**Issue by skynet2982** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6180]
### Website URL

www.ovh.com

### What browser are u using?

Firefox 116.0

### Version

1.1.1

### Notes

On https://www.ovh.com/manager/#/hub

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #756.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
