### ISSUE TITLE
[REQ]: docs.ibracorp.io

### ISSUE THREAD

**Issue by TDWillingham** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6205]
### Website URL

docs.ibracorp.io

### What browser are u using?

Firefox 115.0

### Version

1.1.1

### Notes

Everything working, just the warning.

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #2809.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
