### ISSUE TITLE
[REQ]: larian.com

### ISSUE THREAD

**Issue by Sebster3** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6690]
### Website URL

larian.com

### What browser are u using?

Firefox 117.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #5715.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
