### ISSUE TITLE
[REQ]: www.sachsen-fernsehen.de: Page cannot be scrolled with addon enabled.

### ISSUE THREAD

**Issue by dreirund** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6699]
### Website URL

www.sachsen-fernsehen.de

### What browser are u using?

Firefox 117.0

### Version

1.1.1

### Notes

With the addon enabled, the page cannot be scrolled.

The addon has to be disabled to show the cookie warning, then to interact with it manually. Then the addon can be re-enabled and the page can be scrolled.

**Comment by OhMyGuus** [comment]
Fixed in V1.1.2
