### ISSUE TITLE
[REQ]: ezgif.com

### ISSUE THREAD

**Issue by Daivy03** [OhMyGuus/I-Still-Dont-Care-About-Cookies#6826]
### Website URL

ezgif.com

### What browser are u using?

Chrome 116

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #6420.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
