### ISSUE TITLE
[REQ]: www.instagram.com

### ISSUE THREAD

**Issue by CocoEC** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7097]
### Website URL

www.instagram.com

### What browser are u using?

Firefox 102.0

### Version

1.1.1

### Notes

Cookie consent window still visible

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3103.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
