### ISSUE TITLE
[REQ] www.heise.de

### ISSUE THREAD

**Issue by jamfx** [OhMyGuus/I-Still-Dont-Care-About-Cookies#730]
Website URL

https://heise.de
What browser are u using?

Firefox 107
Version

**Comment by OhMyGuus** [comment]
Can't seem to find any cookie banner on the website ;\

**Comment by jamfx** [comment]
Ok, there is one (see Screenshot attached). But today Cookie-Extension eat it :+1:  I think this can be closed.
![screen](https://user-images.githubusercontent.com/4404552/203947876-7099d9e0-7db9-451f-933e-2ea726129201.png)

**Comment by OhMyGuus** [comment]
Weirdly I get it now as well was most likely a weird issue that it wasn't disabled correctly. 
Seems indeed to work fine now/fixed using request blocking, thanks for the report 👍
