### ISSUE TITLE
[REQ]: www.instagram.com

### ISSUE THREAD

**Issue by Cancoman** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7406]
### Website URL

www.instagram.com

### What browser are u using?

Brave

### Version

1.1.1

### Notes

There is still a Cookie Popup Request that needs to get fixed, because it won't disappear

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3103.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
