### ISSUE TITLE
[REQ] Site request: https://www.make-it-in-germany.com

### ISSUE THREAD

**Issue by Zoomaaa** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7408]
**Website URL(s)**

- [https://www.make-it-in-germany.com](https://www.make-it-in-germany.com)

**Browser**
Firefox 117.0.1 (64-bit)

**Extension version**
V1.1.1

Description:
scrolling is not possible when the extension is enabled on this website.

**Comment by OhMyGuus** [comment]
Fixed in V1.1.2
