### ISSUE TITLE
[REQ]: winfuture.de

### ISSUE THREAD

**Issue by samuelT2** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7457]
### Website URL

winfuture.de

### What browser are u using?

MS Edge

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #1394.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
