### ISSUE TITLE
[REQ]: www.movistar.es

### ISSUE THREAD

**Issue by owolo** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7579]
### Website URL

www.movistar.es

### What browser are u using?

Firefox 117.0

### Version

1.1.1

### Notes

On lower part of the screen.

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3541.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
