### ISSUE TITLE
[REQ]: www.vmock.com

### ISSUE THREAD

**Issue by WonderfulProgress** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7582]
### Website URL

www.vmock.com

### What browser are u using?

Firefox 114.0

### Version

1.1.1

### Notes

Gray overlay, bottom box unable to continue until deny all cookies

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7478.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
