### ISSUE TITLE
[REQ]: www.foodwatch.org

### ISSUE THREAD

**Issue by jensb** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7672]
### Website URL

www.foodwatch.org

### What browser are u using?

Firefox 118.0

### Version

1.1.1

### Notes

cookie warning is displayed despite having the extension

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7338.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
