### ISSUE TITLE
[REQ]: www.spektrum.de

### ISSUE THREAD

**Issue by dreamAviator** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7790]
### Website URL

www.spektrum.de

### What browser are u using?

Firefox 118.0

### Version

1.1.1

### Notes

The cookie banner is not being clicked away.

It's not urgent, I love it, that you made a fork of the original. Thank you!

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #4504.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
