### ISSUE TITLE
[REQ]: nordvpn.com

### ISSUE THREAD

**Issue by C4J3** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7887]
### Website URL

nordvpn.com

### What browser are u using?

Firefox 118.0

### Version

1.1.1

### Notes

I imagine this is a pretty standard one. 

![](https://bit.ly/46H4yRw)

![](https://bit.ly/3Q37wKJ)

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3271.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
