### ISSUE TITLE
[REQ]: hypixel.net

### ISSUE THREAD

**Issue by EliTheCoder** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7972]
### Website URL

hypixel.net

### What browser are u using?

Firefox 118.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #4512.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
