### ISSUE TITLE
[REQ]: www.compact-online.de

### ISSUE THREAD

**Issue by fredo61** [OhMyGuus/I-Still-Dont-Care-About-Cookies#7994]
### Website URL

www.compact-online.de

### What browser are u using?

Firefox 118.0

### Version

1.1.1

### Notes

Privatsphäre-Einstellungen

Wir verwenden Cookies und ähnliche Technologien auf unserer Website und verarbeiten personenbezogene Daten von dir (z.B. IP-Adresse), um z.B. Inhalte und Anzeigen zu personalisieren, Medien von Drittanbietern einzubinden oder Zugriffe auf unsere Website zu analysieren. Die Datenverarbeitung kann auch erst in Folge gesetzter Cookies stattfinden. Wir teilen diese Daten mit Dritten, die wir in den Privatsphäre-Einstellungen benennen.

Die Datenverarbeitung kann mit deiner Einwilligung oder auf Basis eines berechtigten Interesses erfolgen, dem du in den Privatsphäre-Einstellungen widersprechen kannst. Du hast das Recht, nicht einzuwilligen und deine Einwilligung zu einem späteren Zeitpunkt zu ändern oder zu widerrufen. Weitere Informationen zur Verwendung deiner Daten findest du in unserer [Datenschutzerklärung](https://www.compact-online.de/rechtliches/datenschutz/).

Du bist unter 16 Jahre alt? Dann kannst du nicht in optionale Services einwilligen. Du kannst deine Eltern oder Erziehungsberechtigten bitten, mit dir in diese Services einzuwilligen.

Wenn du alle Services akzeptierst, erlaubst du, dass wordpress.com2(Funktional), onesignal2(Funktional), SoundCloud2(Funktional), Vimeo2(Funktional), Twitter (embedded tweet)2(Funktional), videopress2(Funktional), bitchute2(Funktional), Kommentare2(Funktional), Gravatar (Avatar images)2(Funktional), Google User Content2(Funktional), Facebook (embedded post)2(Funktional), Rumble2(Funktional), Odysee2(Funktional), Emojis2(Funktional), Instagram (embedded post)2(Funktional), Kommentare2(Funktional), YouTube2(Funktional), Google Analytics3(Statistik), Google AdSense4(Marketing), Google Ads4(Marketing) und Facebook Page Plugin4(Marketing) geladen werden. Diese sind nach ihrem Zweck in Gruppen Essenziell1, Funktional2, Statistik3 und Marketing4 unterteilt (Zugehörigkeit durch hochgestellte Zahlen gekennzeichnet). Außerdem werden die videopress1(Essenziell) und Elementor1(Essenziell) auf der Grundlage eines berechtigten Interesses geladen.
[Alle akzeptieren](https://www.compact-online.de/skandal-csu-verbietet-compact-berichterstattung/?mc_cid=7a3f3ee2ee#)
[Weiter ohne Einwilligung](https://www.compact-online.de/skandal-csu-verbietet-compact-berichterstattung/?mc_cid=7a3f3ee2ee#)
[Privatsphäre-Einstellungen individuell festlegen](https://www.compact-online.de/skandal-csu-verbietet-compact-berichterstattung/?mc_cid=7a3f3ee2ee#)
[Datenschutzerklärung](https://www.compact-online.de/rechtliches/datenschutz/) • [Datenschutzerklärung](https://www.compact-online.de/rechtliches/datenschutz/) • [Impressum](https://www.compact-online.de/rechtliches/impressum/) • [Impressum](https://www.compact-online.de/rechtliches/impressum/)

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #4802.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
