### ISSUE TITLE
[REQ]: www.nectar.com

### ISSUE THREAD

**Issue by benbristow** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8061]
### Website URL

www.nectar.com

### What browser are u using?

Microsoft Edge (Version 117.0.2045.60 (Official build) (64-bit)

### Version

1.1.1

### Notes

Website doesn't display at all

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3089.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
