### ISSUE TITLE
[REQ]: www.instagram.com

### ISSUE THREAD

**Issue by kimtore** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8090]
### Website URL

www.instagram.com

### What browser are u using?

Firefox 118.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3103.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
