### ISSUE TITLE
[REQ]: www.aliexpress.com

### ISSUE THREAD

**Issue by yakymoto** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8167]
### Website URL

www.aliexpress.com

### What browser are u using?

Firefox 118.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3800.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
