### ISSUE TITLE
[REQ]: www.dropbox.com

### ISSUE THREAD

**Issue by tinkicker** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8586]
### Website URL

www.dropbox.com

### What browser are u using?

Google Chrome 118

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3504.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
