### ISSUE TITLE
[REQ]: lepointdevente.com

### ISSUE THREAD

**Issue by fharper** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8827]
### Website URL

lepointdevente.com

### What browser are u using?

Chromium 119

### Version

1.1.1

### Notes

Got a popup asking my preferences.

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #8826.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
