### ISSUE TITLE
[REQ]: www.unionen.se

### ISSUE THREAD

**Issue by t08** [OhMyGuus/I-Still-Dont-Care-About-Cookies#8966]
### Website URL

www.unionen.se

### What browser are u using?

Firefox 119.0

### Version

1.1.1

### Notes

the cookie promt gets hidden and the site get dim, disable ext solves it

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #8496.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
