### ISSUE TITLE
[REQ]: fr.aliexpress.com

### ISSUE THREAD

**Issue by JacquesFi** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9031]
### Website URL

fr.aliexpress.com

### What browser are u using?

Firefox 119.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7929.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
