### ISSUE TITLE
[REQ]: lecrabeinfo.net

### ISSUE THREAD

**Issue by tonytechlabb** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9074]
### Website URL

lecrabeinfo.net

### What browser are u using?

Brave

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #2580.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
