### ISSUE TITLE
[REQ]: store.duolingo.com

### ISSUE THREAD

**Issue by Voklen** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9110]
### Website URL

store.duolingo.com

### What browser are u using?

Firefox 119.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7661.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
