### ISSUE TITLE
[REQ]: www.hpb.com

### ISSUE THREAD

**Issue by tommymorgan** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9243]
### Website URL

www.hpb.com

### What browser are u using?

Firefox 119.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7842.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
