### ISSUE TITLE
[REQ]: www.trading212.com

### ISSUE THREAD

**Issue by benbristow** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9358]
### Website URL

www.trading212.com

### What browser are u using?

Microsoft Edge for Business

### Version

119.0.2151.58

### Notes

Can't click on links on website

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #6912.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
