### ISSUE TITLE
[REQ]: www.gamivo.com

### ISSUE THREAD

**Issue by darkrei08** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9425]
### Website URL

www.gamivo.com

### What browser are u using?

Firefox 119.0

### Version

1.1.1

### Notes

Addons cannot block coockie banner

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7611.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
