### ISSUE TITLE
[REQ]: 2gis.ru

### ISSUE THREAD

**Issue by torshin** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9439]
### Website URL

2gis.ru

### What browser are u using?

Firefox 119.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #7917.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
