### ISSUE TITLE
[REQ]: www.pccomponentes.com

### ISSUE THREAD

**Issue by JuandePL** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9486]
### Website URL

www.pccomponentes.com

### What browser are u using?

Firefox 119.0

### Version

1.1.1

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #5837.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
