### ISSUE TITLE
Release for Opera?

### ISSUE THREAD

**Issue by d4k0** [OhMyGuus/I-Still-Dont-Care-About-Cookies#95]
Hi,

the original add-on can also be found in the Opera add-ons store. Are there plans to also release this fork there? Opera can also use add-ons from the Chrome store using an additional add-on, but for the average user it would be easier to download it directly from the Opera store.

**Comment by OhMyGuus** [comment]
Yeah!, we are also planning to put in the opera store, sadly opera has the same speeds as chrome to verify the extension so v1.0.3 has been under review for already 5 days already so let's hope they will review it soon.

**Comment by d4k0** [comment]
Thanks for the answer!

**Comment by OhMyGuus** [comment]
Update: I've tried to get it in the opera store, but it doesn't seem possible. 
It seems that they spend all there money on advertisement on Youtube and fired there extension moderation team and our extension isn't eligible for automated review.
