### ISSUE TITLE
[REQ]: www.saturn.de

### ISSUE THREAD

**Issue by NicoWeio** [OhMyGuus/I-Still-Dont-Care-About-Cookies#9578]
### Website URL

www.saturn.de

### What browser are u using?

Firefox 120.0

### Version

1.1.1

### Notes

Scrolling doesn't work

**Comment by OhMyGuus** [comment]
Thank you for reporting this cookie banner or issue.
Closed this issue as it is a duplicate of #3984.
We apologize for any inconvenience and assure you that we are working diligently to implement this website as soon as possible
